version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "/home/znznzn707/containers/zookeeper:/bitnami/zookeeper"
    user: root
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
    - net-kafka
  kafka1:
    image: docker.io/bitnami/kafka:3
    container_name: kafka1
    ports:
      - "9092:9092"
    volumes:
      - "/home/znznzn707/containers/kafka:/bitnami/kafka"
    user: root
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
    - net-kafka
    depends_on:
      - zookeeper
  kafka2:
    image: docker.io/bitnami/kafka:3
    container_name: kafka2
    ports:
      - "9093:9092"
    volumes:
      - "/home/znznzn707/containers/kafka2:/bitnami/kafka"
    user: root
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
    networks:
    - net-kafka
    depends_on:
      - zookeeper
  eagle:
    image: nickzurich/kafka-eagle:latest
    container_name: eagle
    environment:
      EFAK_CLUSTER_ZK_LIST: zookeeper:2181
    networks:
    - net-kafka
    depends_on:
      - kafka1
      - kafka2
    ports:
      - 8048:8048
networks:
  net-kafka: 
    driver: bridge
