version: '3'
services:
  elasticsearch:
    image: elasticsearch
    container_name: es
    networks:
    - net-es
    volumes:
    - /opt/es/data:/usr/share/elasticsearch/data　　#这里将elasticsearch的数据文件映射本地，以保证下次如果删除了容器还有数据
    environment:
    - discovery.type=single-node
    ports:
    - "9200:9200"
 
  es_head:
    image: mobz/elasticsearch-head:5
    container_name: es-head
    networks:
    - net-es
    ports:
      - "9100:9100"
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch:demo"
 
#这里要注意，es和eshd要在相同网络才能被links
networks:
  net-es:
    external: false
