version: "3"

services:
  _mysql:
    image: mysql:5.7.30
    container_name: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - "/home/znznzn707/containers/mysql_mysql/db:/var/lib/mysql"
      - "/home/znznzn707/containers/mysql_mysql/conf:/etc/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root_ROOT
      - MYSQL_USER=Aria
      - MYSQL_PASS=Aria_O
    networks:
    - net_mysql
networks:
  net_mysql:
    driver: bridge
